populationSize: 100
inputSize: 2
outputSize: 1
weightMutationRate: 0.8
weightMutationNudgeMax: 0.5
weightMutationNudgeMin: -0.5
neuronMutationRate: 0.1
axonMutationRate: 0.1
axonMutationRateMaxWeight: 0.5
axonMutationRateMinWeight: -0.5
axonConnectivityMutationRate: 0.1
crossoverRate: 0.8
tournamentSize: 33
maxGenerations: 100
c1: 1.0
c2: 1.0
c3: 0.4
dt: 1.25
